version: '3.3'

services:
  schedulergenerator:
    build: ./SchedulerGenerator
    ports:
      - "7080:80" 
       
    environment:
      - ExternalServices__RecipeApi__Host=tech-test-software-engineer_recipeapi_1
      - ExternalServices__RecipeApi__Port=80
      - ExternalServices__RecipeApi__UseHttps=false
networks:
  default:
    external:
      name: tech-test-software-engineer_default     
      